services:
  my-book-library:
    image: improper/my-book-library:latest
    container_name: my-book-library
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}" # Match to your user
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/storage/logs
      - ./books:/app/storage/app/public/books
